# Generated by Django 5.2.6 on 2025-09-30 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('forma_pago', models.CharField(blank=True, choices=[('Pago a 15 días', 'Pago a 15 días'), ('Pago a 30 días', 'Pago a 30 días'), ('Pago contado', 'Pago contado')], max_length=50, null=True)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50, unique=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estado', models.CharField(default='Disponible', max_length=20)),
                ('categoria', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=400, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('tonelaje', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('carga', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'Maquinaria',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('contacto_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto_email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Obra',
            },
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('periodo', models.CharField(choices=[('Dia', 'Dia'), ('Semana', 'Semana'), ('Mes', 'Mes')], max_length=20)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arriendos', to='api.cliente')),
                ('maquinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arriendos', to='api.maquinaria')),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arriendos', to='api.obra')),
            ],
            options={
                'db_table': 'Arriendo',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Guia Despacho', 'Guia Despacho'), ('Guia Retiro', 'Guia Retiro'), ('Factura', 'Factura')], max_length=30)),
                ('numero', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('archivo_url', models.CharField(blank=True, max_length=200, null=True)),
                ('arriendo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='api.arriendo')),
            ],
            options={
                'db_table': 'Documento',
            },
        ),
    ]
