# Generated by Django 5.2.5 on 2025-08-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('periodo', models.CharField(choices=[('Dia', 'Dia'), ('Semana', 'Semana'), ('Mes', 'Mes')], max_length=20)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='Activo', max_length=20)),
            ],
            options={
                'db_table': 'Arriendo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('forma_pago', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Guia Despacho', 'Guia Despacho'), ('Guia Retiro', 'Guia Retiro'), ('Factura', 'Factura')], max_length=30)),
                ('numero', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('archivo_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50, unique=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estado', models.CharField(default='Disponible', max_length=20)),
            ],
            options={
                'db_table': 'Maquinaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('contacto_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto_email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Obra',
                'managed': False,
            },
        ),
    ]
