# Generated by Django 5.2.6 on 2025-09-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
