# Generated by Django 5.2.6 on 2025-10-19 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usersecurity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALTA', 'Inicio arriendo'), ('PROL', 'Prolongación arriendo'), ('TRAS', 'Traslado (flete entre obras)'), ('RETI', 'Retiro (guía retiro)'), ('SERV', 'Servicio puntual')], max_length=4)),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('PROC', 'Procesada'), ('ANUL', 'Anulada')], default='PEND', max_length=4)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('es_facturable', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'OrdenTrabajo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='api.cliente'),
        ),
        migrations.AddField(
            model_name='documento',
            name='es_retiro',
            field=models.BooleanField(default=False, help_text='Guía de retiro (no facturable)'),
        ),
        migrations.AddField(
            model_name='documento',
            name='monto_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='monto_neto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='obra_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias_entrada', to='api.obra'),
        ),
        migrations.AddField(
            model_name='documento',
            name='obra_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias_salida', to='api.obra'),
        ),
        migrations.AddField(
            model_name='documento',
            name='relacionado_con',
            field=models.ForeignKey(blank=True, help_text='Documento fuente asociado (FACT→GD | NC→FACT | ND→NC)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relaciones_inversas', to='api.documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('FACT', 'Factura'), ('GD', 'Guía de despacho'), ('NC', 'Nota de crédito'), ('ND', 'Nota de débito')], max_length=4),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['tipo', 'numero'], name='Documento_tipo_a75b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['fecha_emision'], name='Documento_fecha_e_27d061_idx'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='arriendo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='api.arriendo'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='api.cliente'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ot_facturadas', to='api.documento'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='guia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ot_guias', to='api.documento'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='maquinaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='api.maquinaria'),
        ),
    ]
