# Generated by Django 5.2.6 on 2025-10-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ordentrabajo_documento_cliente_documento_es_retiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='combustible',
            field=models.CharField(blank=True, choices=[('electrico', 'Eléctrico'), ('diesel', 'Diésel')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='tipo_altura',
            field=models.CharField(blank=True, choices=[('tijera', 'Tijera'), ('brazo', 'Brazo articulado')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='carga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='categoria',
            field=models.CharField(choices=[('equipos_altura', 'Equipos para trabajo en altura'), ('camiones', 'Camiones'), ('equipos_carga', 'Equipos para carga'), ('otro', 'Otro')], default='otro', max_length=32),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Para venta', 'Para venta')], default='Disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='marca',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='modelo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='serie',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='tonelaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterModelTable(
            name='maquinaria',
            table=None,
        ),
    ]
