# Generated by Django 5.2.6 on 2025-11-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_maquinaria_combustible_maquinaria_tipo_altura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='contactos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='detalle_lineas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='monto_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='monto_neto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='obra_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tipo_comercial',
            field=models.CharField(blank=True, choices=[('A', 'Arriendo'), ('V', 'Venta'), ('T', 'Traslado')], help_text='Tipo comercial: A=Arriendo, V=Venta, T=Traslado', max_length=1, null=True),
        ),
    ]
