# Generated by Django 5.2.6 on 2025-12-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ordentrabajo_contactos_ordentrabajo_detalle_lineas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_emision_doc',
            field=models.DateField(blank=True, help_text='Fecha de emisión sugerida para GD/FACT', null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='orden_compra',
            field=models.CharField(blank=True, help_text='OC del cliente asociada a esta OT', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='vendedor',
            field=models.CharField(blank=True, help_text='Nombre del vendedor o ejecutivo comercial', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tipo',
            field=models.CharField(choices=[('ALTA', 'Inicio arriendo'), ('PROL', 'Prolongación arriendo'), ('TRAS', 'Traslado (flete entre obras)'), ('RETI', 'Retiro (guía retiro)'), ('SERV', 'Servicio puntual / Venta')], max_length=4),
        ),
    ]
