# Generated by Django 5.2.17 on 2026-08-08 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_ordentrabajo_fecha_emision_doc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArriendoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arriendo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="api.arriendo",
                    ),
                ),
                (
                    "maquinaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arriendo_items",
                        to="api.maquinaria",
                    ),
                ),
            ],
            options={
                "db_table": "ArriendoItem",
                "indexes": [
                    models.Index(
                        fields=["arriendo", "maquinaria"], name="arri_item_arr_maq_idx"
                    )
                ],
            },
        ),
    ]
